version: '3.7'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Alterado de 3306:3306 para 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
